/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as tokenizedBallotSol from "./TokenizedBallot.sol";
export { MyERC20Token__factory } from "./MyERC20Token__factory";
